name: Build, Test and Version

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch all history for GitVersion
      run: git fetch --prune --unshallow

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.11.0
      with:
        versionSpec: '5.x'

    - name: Run GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.11.0

    - name: Show calculated version
      run: |
        echo GitVersion: ${{ steps.gitversion.outputs.fullSemVer }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish win-x64
      run: dotnet publish -c Release -r win-x64 /p:Version=${{ steps.gitversion.outputs.fullSemVer }}

    - name: Test
      run: dotnet test --no-build --verbosity normal
      continue-on-error: true

    - name: Copy LICENSE to output
      if: success()
      run: copy LICENSE bin/Release/net9.0/win-x64/publish/

    - name: List publish folder before zip
      if: success()
      run: dir bin/Release/net9.0/win-x64/publish

    - name: Publish zip artifact
      if: success()
      run: |
        cd bin/Release/net9.0/win-x64/publish
        del VsExtensionsTool-*.zip 2>NUL
        7z a VsExtensionsTool-${{ steps.gitversion.outputs.assemblySemVer }}.win-x64.zip .\*

    - name: Upload zip to workflow artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: VsExtensionsTool.win-64
        path: bin/Release/net9.0/win-x64/publish/VsExtensionsTool-${{ steps.gitversion.outputs.assemblySemVer }}.win-x64.zip
        if-no-files-found: ignore
        retention-days: 7

    - name: Upload release to GitHub Releases
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: bin/Release/net9.0/win-x64/publish/VsExtensionsTool-${{ steps.gitversion.outputs.assemblySemVer }}.win-x64.zip
